// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	C2SLogin
	S2CLogin
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 登录结果
type LoginResult int32

const (
	LoginResult_Success       LoginResult = 0
	LoginResult_UserNameError LoginResult = -1
	LoginResult_PasswordError LoginResult = -2
	LoginResult_UnknownError  LoginResult = -3
)

var LoginResult_name = map[int32]string{
	0:  "Success",
	-1: "UserNameError",
	-2: "PasswordError",
	-3: "UnknownError",
}
var LoginResult_value = map[string]int32{
	"Success":       0,
	"UserNameError": -1,
	"PasswordError": -2,
	"UnknownError":  -3,
}

func (x LoginResult) String() string {
	return proto.EnumName(LoginResult_name, int32(x))
}
func (LoginResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type C2SLogin_MsgID int32

const (
	C2SLogin_Zero C2SLogin_MsgID = 0
	C2SLogin_ID   C2SLogin_MsgID = 1
)

var C2SLogin_MsgID_name = map[int32]string{
	0: "Zero",
	1: "ID",
}
var C2SLogin_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   1,
}

func (x C2SLogin_MsgID) String() string {
	return proto.EnumName(C2SLogin_MsgID_name, int32(x))
}
func (C2SLogin_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type S2CLogin_MsgID int32

const (
	S2CLogin_Zero S2CLogin_MsgID = 0
	S2CLogin_ID   S2CLogin_MsgID = 2
)

var S2CLogin_MsgID_name = map[int32]string{
	0: "Zero",
	2: "ID",
}
var S2CLogin_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   2,
}

func (x S2CLogin_MsgID) String() string {
	return proto.EnumName(S2CLogin_MsgID_name, int32(x))
}
func (S2CLogin_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// 登陆消息，客户端发送给登录服务器
type C2SLogin struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *C2SLogin) Reset()                    { *m = C2SLogin{} }
func (m *C2SLogin) String() string            { return proto.CompactTextString(m) }
func (*C2SLogin) ProtoMessage()               {}
func (*C2SLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2SLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *C2SLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 登录结果消息，服务器发送给客户端
type S2CLogin struct {
	Result LoginResult `protobuf:"varint,1,opt,name=result,enum=LoginResult" json:"result,omitempty"`
	Token  string      `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *S2CLogin) Reset()                    { *m = S2CLogin{} }
func (m *S2CLogin) String() string            { return proto.CompactTextString(m) }
func (*S2CLogin) ProtoMessage()               {}
func (*S2CLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2CLogin) GetResult() LoginResult {
	if m != nil {
		return m.Result
	}
	return LoginResult_Success
}

func (m *S2CLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*C2SLogin)(nil), "C2SLogin")
	proto.RegisterType((*S2CLogin)(nil), "S2CLogin")
	proto.RegisterEnum("LoginResult", LoginResult_name, LoginResult_value)
	proto.RegisterEnum("C2SLogin_MsgID", C2SLogin_MsgID_name, C2SLogin_MsgID_value)
	proto.RegisterEnum("S2CLogin_MsgID", S2CLogin_MsgID_name, S2CLogin_MsgID_value)
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x8a, 0xe5, 0xe2, 0x70, 0x36, 0x0a,
	0xf6, 0xc9, 0x4f, 0xcf, 0xcc, 0x13, 0x92, 0xe2, 0xe2, 0x28, 0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x05, 0x89, 0xc5, 0xc5,
	0xe5, 0xf9, 0x45, 0x29, 0x12, 0x4c, 0x10, 0x39, 0x18, 0x5f, 0x49, 0x92, 0x8b, 0xd5, 0xb7, 0x38,
	0xdd, 0xd3, 0x45, 0x88, 0x83, 0x8b, 0x25, 0x2a, 0xb5, 0x28, 0x5f, 0x80, 0x41, 0x88, 0x8d, 0x8b,
	0xc9, 0xd3, 0x45, 0x80, 0x51, 0x29, 0x91, 0x8b, 0x23, 0xd8, 0xc8, 0x19, 0x62, 0xbc, 0x0a, 0x17,
	0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e, 0x09, 0xd8, 0x70, 0x3e, 0x23, 0x1e, 0x3d, 0xb0, 0x78, 0x10,
	0x58, 0x2c, 0x08, 0x2a, 0x27, 0x24, 0xc2, 0xc5, 0x5a, 0x92, 0x9f, 0x9d, 0x9a, 0x07, 0xb5, 0x05,
	0xc2, 0xc1, 0x6d, 0x05, 0x93, 0x56, 0x2e, 0x17, 0x37, 0x92, 0x39, 0x42, 0xdc, 0x5c, 0xec, 0xc1,
	0xa5, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5, 0x02, 0x0c, 0x42, 0x52, 0x5c, 0xbc, 0xa1, 0xc5, 0xa9, 0x45,
	0x7e, 0x89, 0xb9, 0xa9, 0xae, 0x45, 0x45, 0xf9, 0x45, 0x02, 0xff, 0x61, 0x80, 0x11, 0x24, 0x17,
	0x00, 0xf5, 0x01, 0x44, 0xee, 0x1f, 0x42, 0x4e, 0x92, 0x8b, 0x27, 0x34, 0x2f, 0x3b, 0x2f, 0xbf,
	0x3c, 0x0f, 0x22, 0xf5, 0x17, 0x2e, 0x95, 0xc4, 0x06, 0x0e, 0x37, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd4, 0x24, 0x12, 0x6d, 0x48, 0x01, 0x00, 0x00,
}
